services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  postgresql:
    container_name: postgresql
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  pgadmin:
    container_name: pgadmin_container
    user: root
    image: dpage/pgadmin4:6.19

    depends_on:
      - postgresql

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80

  backend_app:
    container_name: archive-app_backend
    environment:
      - "DB_HOST=postgresql"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    image: archiveapp-backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/app/build
    ports:
      - "8081:8080"
    depends_on:
      - nginx
      - postgresql

  client_app:
    image: archiveapp-client:0.0.1
    build:
      context: client
      dockerfile: ./Dockerfile
    depends_on:
      - nginx